// Package repository provides the data-access layer for the parser-service.
//
// All database interactions (PostgreSQL for persistent storage, Redis for
// ephemeral order matching) are abstracted behind interfaces so that the
// service layer remains decoupled from specific storage technologies.
package repository

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	"github.com/shopspring/decimal"
)

// SMSMessage represents a row in the sms_messages table. Every incoming
// SMS that passes anti-spoofing validation is persisted here, regardless
// of whether it is successfully matched to an order. This creates a
// complete audit trail of all bank notifications the system has received.
type SMSMessage struct {
	// ID is the unique identifier for this SMS record (UUID v4).
	ID uuid.UUID

	// BankAccountID links the SMS to the internal bank account that received
	// the transfer. Determined by mapping the SMS sender number to a
	// configured bank account.
	BankAccountID uuid.UUID

	// BankCode is the short bank identifier (e.g. "KBANK", "SCB").
	BankCode string

	// SenderNumber is the phone number or alphanumeric ID that sent the SMS.
	SenderNumber string

	// Amount is the parsed transaction amount in THB.
	Amount decimal.Decimal

	// SenderName is the name of the person who initiated the transfer,
	// as extracted from the SMS text.
	SenderName string

	// Reference is the bank transaction reference or partial account number.
	Reference string

	// RawMessage is the original, unmodified SMS text for audit purposes.
	RawMessage string

	// MatchedOrderID is set when this SMS has been successfully matched to
	// a pending deposit order. It is nil when the SMS is unmatched.
	MatchedOrderID *uuid.UUID

	// Status indicates the current state of this SMS record.
	// Possible values: "matched", "unmatched", "error".
	Status string

	// ReceivedAt is when the SMS gateway reports having received the message.
	ReceivedAt time.Time

	// CreatedAt is when this record was inserted into the database.
	CreatedAt time.Time
}

// SMSRepository defines the interface for persisting and querying SMS messages.
// Implementations must be safe for concurrent use from multiple goroutines.
type SMSRepository interface {
	// Store inserts a new SMSMessage into the sms_messages table.
	// The msg.ID must be pre-generated by the caller.
	// Returns an error if the insert fails (e.g. duplicate ID, connection issue).
	Store(ctx context.Context, msg *SMSMessage) error
}

// PendingOrderInfo holds the minimal information about a pending deposit
// order that is cached in Redis for fast SMS-to-order matching. The full
// order details live in PostgreSQL; Redis only stores what the matcher needs.
type PendingOrderInfo struct {
	// OrderID is the unique identifier of the deposit order.
	OrderID uuid.UUID

	// BankAccountID is the bank account the customer was told to transfer to.
	BankAccountID uuid.UUID

	// Amount is the adjusted (unique) amount the customer should transfer.
	Amount decimal.Decimal
}

// OrderMatcher defines the interface for matching incoming SMS transactions
// against pending deposit orders stored in Redis. The order-service writes
// pending orders into Redis; the parser-service reads them here.
type OrderMatcher interface {
	// FindPendingOrder looks up a pending order in Redis by bank account ID
	// and exact amount. Returns nil (without error) if no match is found.
	//
	// Parameters:
	//   - ctx:           request-scoped context for cancellation/timeout.
	//   - bankAccountID: the internal bank account that received the transfer.
	//   - amount:        the exact transfer amount to match against.
	//
	// Returns:
	//   - A PendingOrderInfo if a match is found, nil otherwise.
	//   - An error only if the Redis query itself fails.
	FindPendingOrder(ctx context.Context, bankAccountID uuid.UUID, amount decimal.Decimal) (*PendingOrderInfo, error)
}

// ----- PostgreSQL implementation -----

// PostgresSMSRepository implements SMSRepository using PostgreSQL via pgxpool.
// It stores SMS messages in the sms_messages table for persistent audit trails.
type PostgresSMSRepository struct {
	// pool is the PostgreSQL connection pool shared across all queries.
	pool *pgxpool.Pool
}

// NewPostgresSMSRepository creates a new PostgresSMSRepository backed by
// the given connection pool. The pool must already be connected and healthy.
func NewPostgresSMSRepository(pool *pgxpool.Pool) *PostgresSMSRepository {
	return &PostgresSMSRepository{pool: pool}
}

// Store inserts an SMSMessage into the sms_messages table.
// All fields are written in a single INSERT statement. The caller is
// responsible for generating msg.ID (UUID v4) before calling this method.
//
// Parameters:
//   - ctx: request-scoped context for cancellation and timeout.
//   - msg: the fully populated SMS message to persist.
//
// Returns:
//   - An error if the INSERT fails (e.g. constraint violation, connection loss).
func (r *PostgresSMSRepository) Store(ctx context.Context, msg *SMSMessage) error {
	// language=SQL
	const query = `
		INSERT INTO sms_messages (
			id, bank_account_id, bank_code, sender_number, amount,
			sender_name, reference, raw_message, matched_order_id,
			status, received_at, created_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`

	_, err := r.pool.Exec(ctx, query,
		msg.ID,
		msg.BankAccountID,
		msg.BankCode,
		msg.SenderNumber,
		msg.Amount,
		msg.SenderName,
		msg.Reference,
		msg.RawMessage,
		msg.MatchedOrderID,
		msg.Status,
		msg.ReceivedAt,
		msg.CreatedAt,
	)
	if err != nil {
		return fmt.Errorf("sms_repo: insert failed: %w", err)
	}
	return nil
}

// ----- Redis implementation -----

// RedisOrderMatcher implements OrderMatcher using Redis. Pending deposit
// orders are stored in Redis by the order-service with keys formatted as:
//
//	pending_order:{bank_account_id}:{amount}
//
// The value is the order UUID. This key structure allows O(1) lookups by
// the exact (bank_account_id, amount) pair that the SMS parser extracts.
type RedisOrderMatcher struct {
	// client is the Redis client used for all queries.
	client *redis.Client
}

// NewRedisOrderMatcher creates a new RedisOrderMatcher backed by the given
// Redis client. The client must already be connected and healthy.
func NewRedisOrderMatcher(client *redis.Client) *RedisOrderMatcher {
	return &RedisOrderMatcher{client: client}
}

// FindPendingOrder queries Redis for a pending order matching the given
// bank account and amount. The key format mirrors what the order-service
// writes: "pending_order:{bankAccountID}:{amount}".
//
// Parameters:
//   - ctx:           request-scoped context for cancellation/timeout.
//   - bankAccountID: the UUID of the bank account that received the transfer.
//   - amount:        the exact transfer amount (must match to the cent).
//
// Returns:
//   - A PendingOrderInfo if a matching key exists in Redis.
//   - nil (with nil error) if no matching key is found (redis.Nil).
//   - An error if the Redis GET command fails for any other reason.
func (m *RedisOrderMatcher) FindPendingOrder(ctx context.Context, bankAccountID uuid.UUID, amount decimal.Decimal) (*PendingOrderInfo, error) {
	// Build the Redis key using the same format the order-service writes.
	// Amount is formatted without trailing zeros for consistent key matching.
	key := fmt.Sprintf("pending_order:%s:%s", bankAccountID.String(), amount.String())

	// Attempt to retrieve the order ID from Redis.
	orderIDStr, err := m.client.Get(ctx, key).Result()
	if err == redis.Nil {
		// No matching pending order found - this is a normal case,
		// not an error. The SMS will be marked as unmatched.
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("redis: get pending order: %w", err)
	}

	// Parse the stored order UUID.
	orderID, err := uuid.Parse(orderIDStr)
	if err != nil {
		return nil, fmt.Errorf("redis: invalid order UUID %q: %w", orderIDStr, err)
	}

	return &PendingOrderInfo{
		OrderID:       orderID,
		BankAccountID: bankAccountID,
		Amount:        amount,
	}, nil
}
